version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: pnpm dev --filter api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    ports:
      - "4000:4000"
    environment:
      - SERVICE_TYPE=Gateway
  wallet:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: pnpm dev --filter api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    ports:
      - "4000"
    environment:
      - SERVICE_TYPE=Wallet

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

volumes:
  mongo-data:
